name: Build and Deploy Java Web Server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Build Java Web Server
        run: mvn clean install
      - name: Run Maven Unit Tests
        run: mvn test
      - name: Initialize Terraform
        run: terraform init
      - name: Deploy Java Web Server to EC2
        uses: hashicorp/terraform@v1.2.1
        with:
          tf_actions_version: "1.2.1"
          tf_actions_subcommand: "apply"
          tf_actions_comment: "Deploying Java Web Server to EC2"
          tf_actions_auto_approve: "true"
          entryPoint: terraform
          args: apply -auto-approve
