name: Java Webserver Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Compile Java Webserver
        run: javac Webserver.java
      - name: Run Maven Unit Tests
        run: mvn test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Configure Terraform
        run: terraform init
      - name: Deploy Java Webserver to EC2
        run: terraform apply
