name: Build and Deploy Java Web Server
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Java Web Server
        run: mvn clean install
      - name: Run Maven Unit Tests
        run: mvn test
      - name: Deploy Java Web Server to EC2
        uses: hashicorp/terraform@v1.2.1
        with:
          entryPoint: apply
          args: -auto-approve
